[package]
name = "wizard"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = false
publish = false

[lib]
name = "wizard_lib"

[lints]
workspace = true

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
serde_json = { workspace = true, features = ["std"] }
tauri = { workspace = true, features = [] }
tauri-plugin-single-instance.workspace = true
tauri-plugin-updater.workspace = true
tokio.workspace = true
