[package]
name = "ff-wizard"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = false
publish = false

[lib]
# Keep the library name distinct from the binary name on Windows.
name = "ff_wizard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[lints]
workspace = true

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
serde_json = { workspace = true, features = ["std"] }
tauri = { workspace = true, features = [] }
tauri-plugin-updater.workspace = true
