[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = false
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
semver.workspace = true
serde_json.workspace = true
tempfile.workspace = true
