[package]
name = "wizard-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = false
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
wizard-core = { path = "../wizard-core" }
